server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

logging:
  level:
    org.springframework: INFO
    com.biomedmanager: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Uncomment and configure these if using Spring Security
# security:
#   user:
#     name: admin
#     password: admin

app:
  notification:
    email:
      enabled: false
    sms:
      enabled: false

# Sample configuration for email notifications (if enabled)
# spring:
#   mail:
#     host: smtp.example.com
#     port: 587
#     username: your-email@example.com
#     password: your-email-password
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true

# Sample configuration for external API keys
# external:
#   api:
#     key: your-api-key-here
